---
- hosts: new
  tasks:
  - name: gpg key
    apt_key: url=https://apt.dockerproject.org/gpg state=present

  - name: Apt upd & docker instal
    apt_repository: repo="deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main" state=present update_cache=yes

  - name: install pip and docker
    apt: name={{item}} state=present update_cache=yes
    with_items:
     - docker-engine
     - python-pip

  - name: Pip module
    pip: name={{item}} state=present
    with_items:
     - docker-py
     - docker-compose

  - name: going to work
    shell: docker pull pwinik/hword
    shell: docker run -d -p 176.57.208.18:32890:8081 pwinik/hword
